# Generated by Django 5.0.3 on 2024-04-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmodal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModal',
        ),
    ]
